### ISSUE TITLE
Application creation

### ISSUE THREAD

**Issue by Sthopeless** [tonyldo/ttlockio#1]
Hi! 
Thanks for this and the integration with Home Assistant, I have long been waiting for this! 

I have created a application to get started and am waiting for the review to be confirmed, meanwhile I'd like to check.

Does it matter which `Application url` and `Redirect url` we use?

**Comment by tonyldo** [comment]
Hi there! I still working at same time on:

- This Repo - TTLockIo  - a lib that will be upload to PiPy repo, and I will use in my other projects, listed below...
- A  TTLocktoMQTT adapter - this can be use as addon on Hass to make a clue between TTLock and the mqtt lock integration https://www.home-assistant.io/integrations/lock.mqtt/
- The lock.ttlock a full integration for TTLock on Hass. This will take some time. :)

About the urls, I dont think that "Application url" has used for something, i put my hass duck dns url. And the "Redirect url", you can put any valid url.

**Comment by Sthopeless** [comment]
Hi @tonyldo and thank you for the reply! 

Looks great! I hadn't seen yet the TTLocktoMQTT project! 

I have one TTLock Door and I've bought the "G2 Gateway" in hopes it had a ESP8266 inside and I could make it work with Tasmota.
The gateway has a esp8266 inside and I managed to flash Tasmota but no luck yet getting signals from the main MCU.
And because the main MCU resets the ESP8266 after a few minutes my original firmware backup is corrupted so i dont have change to dig more into it.
I have trade same emails with TTLock dev they seemed kind and helpful but once I requested a backup of the firmware to fix my device they stop emailing me :)

My application on TTLock page still 'under review' once is reviewed I'll give it a go. 

Thank you and let me know if there is anyway I can help.

**Comment by tonyldo** [comment]
Wow, I have only one gateway :) I can get risks.
So you will need a gateway to use the api... There is no other way to get access to the TTlock Cloud API.
My application review took one month.

**Comment by Sthopeless** [comment]
hi @tonyldo! 

I finally have new gateway working my application is reviewed and meanwhile I discovered my door lock doesn't work with my new phone but I can use it on my tablet without problems.

I have also received a WiFi Tuya Door Lock with a esp8266 I will be doing some digging when I have some time.

Yesterday I had a go at this to see if I could finally install my door locks :smile: I tried `lock.ttlock` which didn't work and adding `TTLockToMQTT` url to my HASS addons didn't show any available to install, could you tell me how to get started? 

Thank you again this project has great potential.

Regards

**Comment by botts7** [comment]
Hi There, Thank you for creating this.

I have had success creating users and getting keys etc.

But I can not login with the created user with TTlock app

The App asks for Phone or Email as user name, but the user requirements of the API state it needs to be numbers or letters so cant use email address?

Can you please explain what I am doing wrong? Or why the user name and password I have may not be working?

Thanks
