### ISSUE TITLE
api.ttlock.com is deprecated. Request for configurable domain name (and maybe change default to euapi.ttlock.com)

### ISSUE THREAD

**Issue by ndbroadbent** [tonyldo/ttlockio#11]
I got the message below. `api.ttlock.com` is deprecated and will no longer work next month. Could you please release a new version with an updated or configurable domain? Thanks!

-----

Dear Developer,

In response to the legal requirements for better data security and privacy protection, we have assigned different domain names to users from China and other countries. Please be reminded to update the domain name if you are using any of our API. For software used in China, please call the China domain name. Otherwise, please call the domain name for users out of China. Following are the details：

Original domain name: [api.ttlock.com 1](http://api.ttlock.com/)
New domain name (China): [cnapi.ttlock.com](http://cnapi.ttlock.com/)
New domain name (Out of China): [euapi.ttlock.com 1](http://euapi.ttlock.com/)

Original domain name: [api.sciener.com 1](http://api.sciener.com/)
New domain name (China): [cnapi.sciener.com](http://cnapi.sciener.com/)
New domain name (Out of China): [euapi.sciener.com](http://euapi.sciener.com/)

The original domain name will be deleted and no longer in service after Oct. 1st, 2022. Your speedy action is highly appreciated.

If you need any assistance, please feel free to contact us at [dev@ttlock.com](mailto:dev@ttlock.com)

Best Regards,
Sciener/TTLock Team

**Comment by tonyldo** [comment]
i update base url at this lib... i will start test and update ttlock2mqtt addon this weekend.

**Comment by ndbroadbent** [comment]
Thank you very much!

**Comment by tonyldo** [comment]
Lib update to 0.3.1
