### ISSUE TITLE
Error returned from TTlockAPI: Error_code 10007 - invalid account or invalid password

### ISSUE THREAD

**Issue by stevendodd** [tonyldo/ttlockio#12]
Do you also need to update the token URLs

```
>>> token=TTLock.get_token(clientId,clientSecret,user,password,redirect_url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ttlockwrapper/ttlock.py", line 60, in get_token
    return TTLock.__send_request__(_url_request,'POST').json()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ttlockwrapper/ttlock.py", line 28, in __send_request__
    raise TTlockAPIError(error_code=_response.json().get(ERROR_CODE_FIELD),menssage=_response.json().get(MENSSAGE_FIELD))
ttlockwrapper.ttlock.TTlockAPIError: Error returned from TTlockAPI: Error_code 10007 - invalid account or invalid password
>>
```

**Comment by tonyldo** [comment]
This is not wrong URL error. So It is responding a API ttlock error.

**Comment by stevendodd** [comment]
I have valid credentials and I am passing in a non md5 hashed password; somethings not right

**Comment by tonyldo** [comment]
If u have knowlege try validated your credencial using API client likely postman.

**Comment by stevendodd** [comment]
I can confirm they work via the API

**Comment by stevendodd** [comment]
`{"adminPwd":"xx","aesKeyStr":"xx","autoLockTime":5,"date":1649189534000,"deletePwd":"","displayPasscode":0,"electricQuantity":100,"featureValue":"C2F44354CF5F7","firmwareRevision":"6.4.08.211208","hardwareRevision":"1.6","hasGateway":1,"keyboardPwdVersion":4,"lockAlias":"Home","lockFlagPos":0,"lockId":xx,"lockKey":"xxx","lockMac":"xx","lockName":"xx","lockSound":1,"lockUpdateDate":1662991770000,"lockVersion":{"groupId":10,"orgId":34,"protocolType":5,"protocolVersion":3,"scene":2},"modelNum":"xx","noKeyPwd":"xxx","openDirection":0,"passageMode":2,"passageModeAutoUnlock":2,"privacyLock":2,"resetButton":1,"sensitivity":0,"soundVolume":5,"specialValue":xxx,"tamperAlert":1,"timezoneRawOffset":3600000}`

**Comment by tonyldo** [comment]
i test again and it is working...

```
>>> import ttlockwrapper
>>> result_user=ttlockwrapper.TTLock.create_user('*******************','**************','tester1','123456abcde').get('username')
>>> print(result_user)
homeassistant_tester1
>>> token=ttlockwrapper.TTLock.get_token('*****************','********************','homeassistant_tester1','123456abcde','https://**********.duckdns.org/')
>>> print(token)
{'access_token': '*********************', 'uid': 12007440, 'refresh_token': '*************************', 'openid': 1627987697, 'scope': 'user,key,room', 'token_type': 'Bearer', 'expires_in': 7776000}
>>> 
```

**Comment by stevendodd** [comment]
I can confirm that if I create a user with your code I can then get an access token. If I try to generate a token with an existing user it fails with an invalid account. It's probably a difference between the hash for the password, I created my hashed password using: `echo "password" | md5`

**Comment by tonyldo** [comment]
The ttlockio uses the hashlib package for this...
```
hashlib.md5(password.encode()).hexdigest(),
```
