### ISSUE TITLE
Error when installing library

### ISSUE THREAD

**Issue by stevendodd** [tonyldo/ttlockio#16]
```
Successfully built ttlockio
Installing collected packages: ttlockio
ERROR: For req: ttlockio==0.3.2. Invalid script entry point: <ExportEntry create_access_token = bin.create_access_token:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information.
```

**Comment by tonyldo** [comment]
Please, can u edit the readme file describe the step 4 and how to get the credentials?

**Comment by stevendodd** [comment]
The scripts don't work as you originally intended; perhaps the build process has changed since you originally wrote it however whenever you install version 0.3.2 you get an error and the script is not working as it may be did before.

Script endpoints defined in the toml file need to invoke methods that don't take any parameters - this obviously prevents passing in client secrets/IDs et cetera to the method.

I have updated the toml to point to the respective methods within your class which removes the errors from the install however the scripts still do not work as intended.

I will dig a little bit deeper to see if it is indeed possible to pass parameters into the scrips but as yet I've not found a way

**Comment by tonyldo** [comment]
i understand this... in fact some scripts doesnt run since the migration for build package to toml. 
but what i m say is: try to write something like:
Step 4:
 - install ttlockio python package:
pip install ....
- enter python repl console
python3
import ttlockio
 print (ttlockio.get_token())...

Do you get it?

**Comment by stevendodd** [comment]
yes; alternatively I can add entry point methods to your main class

def add_user_entry():
  prompt for input
  user = create_user(cls,clientId,clientSecret,username,password)
  print user

Would you want these additional methods in your main class? Or shall I just update the documentation to use the python console as you suggest

**Comment by tonyldo** [comment]
As u wish, Steven... And thank you for help me.
I dont have so much time to keeping update this lib. Thank you very much!

**Comment by ndbroadbent** [comment]
Hello, I'm trying to get this updated for my front door lock (using https://github.com/tonyldo/tonyldo-hassio-addons). `0.3.1` and `0.3.2` are both crashing when docker is running `pip install`.

Is this a quick fix? If not, would it be possible to revert the recent changes and release a new working version (also with the base URL updated?) Thanks!

**Comment by stevendodd** [comment]
@ndbroadbent its fixed in 0.3.3 - I just need to finish this PR so it can be pushed to PYPI.

I don't think it's a recent problem I suspect it was also in the version before the Apis were updated recently - I will get my PR completed at the latest this weekend and hopefully Anthony will be able to push it

**Comment by tonyldo** [comment]
Hello, i think that @ndbroadbent has his own repository for TTlock2Mqtt addon and he is trying to update the lib, but it no ready @ndbroadbent! Still on 0.21.

**Comment by ndbroadbent** [comment]
Thank you! No hurry though, I was able to fix the issue in my fork and have got it working again. But would be great to stop using a fork and go back to the released version. Thanks everyone for all your work!

**Comment by stevendodd** [comment]
could you please push to pypi

**Comment by tonyldo** [comment]
> could you please push to pypi

Done!
