### ISSUE TITLE
User name not valid in ttlock app

### ISSUE THREAD

**Issue by botts7** [tonyldo/ttlockio#2]
Hi There, Thank you for creating this.

I have had success creating users and getting keys etc.

But I can not login with the created user with TTlock app

The App asks for Phone or Email as user name, but the user requirements of the API state it needs to be numbers or letters so cant use email address?

Can you please explain what I am doing wrong? Or why the user name and password I have may not be working?

Thanks

**Comment by tonyldo** [comment]
Hi, Thanks for following my project...
Do you try this steps from the README in this repo:
```
Create a user for this application:
$ curl --location --request POST 'https://api.ttlock.com/v3/user/register?clientId=YOUR_APP_CLIENT_ID&clientSecret=YOUR_APP_CLIENTSECRET&username=NEW_NAME_FOR_YOUR_USER&password=NEW_PASS_FOR_YOUR_USER&date=CURRENTMILLIS' \
--header 'Content-Type: application/x-www-form-urlencoded' \
ATTENTION: you need pass the NEW_PASS_FOR_YOUR_USER with max 32 chars, low case and md5 encrypted
```
When do you say "creating users and getting keys etc" is the TTLock Api Client application?

**Comment by botts7** [comment]
Hi,

after doing 

`curl --location --request POST 'https://api.ttlock.com/v3/user/register?clientId=YOUR_APP_CLIENT_ID&clientSecret=YOUR_APP_CLIENTSECRET&username=NEW_NAME_FOR_YOUR_USER&password=NEW_PASS_FOR_YOUR_USER&date=CURRENTMILLIS' \
--header 'Content-Type: application/x-www-form-urlencoded' \`

I get result: APP_NAME_USER (eg: MYAPP_FRED)

the password I entered for "NEW_PASS_FOR_YOUR_USER" was text converted to MD5 using a MD5 Hash Generator

When trying to log in to the  TTlock app from the app store I am prompted to enter user name and password

I enter:

user: MYAPP_FRED 
pass: "text I entered into MD5 Hash Generator (not the MD5 hash)" eg: mypass

The app prompts me user name or password incorrect

All your curl commands return result as expected, just cant log into the app from the appstore using the credentials

**Comment by botts7** [comment]
Worked it out - I tried a different MD5 Encryption website and now I am logged into app

Can wait to get this working in home assistant

**Comment by botts7** [comment]
Sorry just for clarity - is the home assistant component stand alone - or do I need to install ttlockio and the TTlock2mqtt as well?

**Comment by tonyldo** [comment]
> Sorry just for clarity - is the home assistant component stand alone - or do I need to install ttlockio and the TTlock2mqtt as well?

https://github.com/tonyldo/ttlockio/issues/1#issuecomment-626192074

**Comment by Sthopeless** [comment]
@tonyldo I've managed to install TTlock2MQTT hassio addon and I have added my lock and gateway to the new account I have created, on the addon log I can see:
```
2020-07-26 23:49:23 - [INFO] ttlock_adapter: Created TTlock Mqtt Client for lockid: lOCK-1861714-1595800163
2020-07-26 23:51:24 - [INFO] ttlock_adapter: Current threads: 2
2020-07-26 23:52:24 - [INFO] ttlock_adapter: Created TTlock Mqtt Client for lockid: lOCK-1861714-1595800344
2020-07-26 23:54:24 - [INFO] ttlock_adapter: Current threads: 2
```
But I can't find any activity on my MQTT broker nor my lock is added to Home Assistant, what am I missing?

**Comment by tonyldo** [comment]
> @tonyldo I've managed to install TTlock2MQTT hassio addon and I have added my lock and gateway to the new account I have created, on the addon log I can see:
> 
> ```
> 2020-07-26 23:49:23 - [INFO] ttlock_adapter: Created TTlock Mqtt Client for lockid: lOCK-1861714-1595800163
> 2020-07-26 23:51:24 - [INFO] ttlock_adapter: Current threads: 2
> 2020-07-26 23:52:24 - [INFO] ttlock_adapter: Created TTlock Mqtt Client for lockid: lOCK-1861714-1595800344
> 2020-07-26 23:54:24 - [INFO] ttlock_adapter: Current threads: 2
> ```
> 
> But I can't find any activity on my MQTT broker nor my lock is added to Home Assistant, what am I missing?

When you discovery what is happening please tell me... Ha ha ha 
Something is wrong with the MQTT connection. This is my first time build a hassio addon... I am doing something wrong. But i Will fix this, dont worry.

**Comment by Sthopeless** [comment]
At least is not something I am doing wrong, I was already creating new MQTT usernames & passwords to see if mine were to "complicated". 

Have you somehow been able to add TTLocks to HA, if so would you mind sharing how?

Have you thought about sharing your TTLocks projects on Home Assistant forums?
I have seen more people are looking for this and maybe one of them can help debug the problems?

**Comment by Sthopeless** [comment]
@tonyldo if i rename this line like this https://github.com/Sthopeless/TTLockToMQTT/blob/master/ttlocktomqtt/src/ttlock_adapter.py#L18

I get this on my logs `2020-07-27 00:45:57 - [INFO] ttlock_adapter: Return future for lockid: ttlock` 
not sure if its relevant.

**Comment by botts7** [comment]
> > @tonyldo I've managed to install TTlock2MQTT hassio addon and I have added my lock and gateway to the new account I have created, on the addon log I can see:
> > ```
> > 2020-07-26 23:49:23 - [INFO] ttlock_adapter: Created TTlock Mqtt Client for lockid: lOCK-1861714-1595800163
> > 2020-07-26 23:51:24 - [INFO] ttlock_adapter: Current threads: 2
> > 2020-07-26 23:52:24 - [INFO] ttlock_adapter: Created TTlock Mqtt Client for lockid: lOCK-1861714-1595800344
> > 2020-07-26 23:54:24 - [INFO] ttlock_adapter: Current threads: 2
> > ```
> > 
> > 
> > But I can't find any activity on my MQTT broker nor my lock is added to Home Assistant, what am I missing?
> 
> When you discovery what is happening please tell me... Ha ha ha
> Something is wrong with the MQTT connection. This is my first time build a hassio addon... I am doing something wrong. But i Will fix this, dont worry.

Have you tried turning on debug logging in home assistant to get additional logs?

**Comment by Sthopeless** [comment]
@botts7 MQTT messages were kinda working in this commit https://github.com/tonyldo/TTLockToMQTT/tree/d162d1d37e598458d4259858e2681528e67789c8
I had messages being posted on my broker to topic `ttlocktomqtt/1861714/state` and `ttlocktomqtt/1861714/battery` battery level were correct but state was always locked and there were also messages posts in the topic `homeassistant/lock/ttlock/1861714_lock/config` containing ```{"name": "2017MM_6f3aa5", "command_topic": "ttlocktomqtt/1861714/command", "state_topic": "ttlocktomqtt/1861714/state", "value_template": "{ value_json.command}", "uniq_id":"1861714_lock","device":{"identifiers":["1861714"],"connections":[["mac","xx:xx:xx:xx:xx:xx"]]}, "via_device":"44870" }``` Name and MAC match my lock.

**Comment by tonyldo** [comment]
hello everyone, i will close this issue.. i have released the ttlocktomqtt beta and open the issue page of that github repo. 
Lets go there... and thanks to every one.

**Comment by Chiga75** [comment]
Hi,
First of all thank you for creating this add.
I have already had success creating users and getting keys and everything what you wrote. 
But the HA still didn't discover my unit. If I check the log file I get below log. 
Can you help me what I made wrong?

2022-03-08 21:03:45 - [INFO] TTLOCK2MQTT: Current threads: 1
2022-03-08 21:03:45 - [INFO] TTLOCK2MQTT: Current threads: 1
2022-03-08 21:03:46 - [INFO] TTLOCK2MQTT: Current threads: 1

**Comment by tonyldo** [comment]
Can u please send yours addon configuration? Remove yours credentials for security reasons!

**Comment by Chiga75** [comment]
Thank you for the fast replay.
of course 
Here you are
![mqtt](https://user-images.githubusercontent.com/86006126/157319679-bccd82f3-8ca4-426b-8351-cfe5c27d85d4.jpg)

**Comment by tonyldo** [comment]
try change the loglevel to debug  ... let s see if we can find something else

**Comment by Chiga75** [comment]
Here you are:
![mq2](https://user-images.githubusercontent.com/86006126/157322335-8a10837e-8c03-4d77-b298-422621da74c9.jpg)

**Comment by tonyldo** [comment]
If u have skills with some api client like "postman" try these request: https://api.ttlock.com/v3/gateway/list? ....

**Comment by Chiga75** [comment]
here is the result
{"total":0,"pages":0,"pageNo":1,"pageSize":20,"list":[]}
If i connect with the mobile app i see 3 locks

**Comment by tonyldo** [comment]
u need access your mobile app with the SAME USER that used in TTLOCKIO and add yours devices (gateways) again.

**Comment by Chiga75** [comment]
Probably it was a problem.
I add a same user in TTLOCKIO just didn't attached gateway directly, I just gave lock admin permission from another account.
Now I add a gateway but i got this message in the log.
![gatew](https://user-images.githubusercontent.com/86006126/157337010-654a7e04-73d9-45f6-b0df-357bdffe744e.jpg)

**Comment by tonyldo** [comment]
Now we are seeing another problem. U have a problem with the mqtt broker connection. So the previous problem appears to be solved. Try test yours connection with the mqtt server ! 


Edit: in yours addon configuration u forgoten the mqtt broker host!?

**Comment by Chiga75** [comment]
Yes it was the problem. now looks working fine. Thank you for your help!
