### ISSUE TITLE
Is it possible to use an MQQT Broker other than one in HA?

### ISSUE THREAD

**Issue by Wheresitat** [tonyldo/ttlockio#20]
I am running my MQQT broker on docker, so it has a different IP address to my HA OS.
I can't see a way to point TTLock2MQTT to a different MQQT broker IP? Is it possible?

**Comment by tonyldo** [comment]
No, it's not possible now... Today ttlock2mqtt uses the mqtt addon from HASS.
https://developers.home-assistant.io/docs/add-ons/communication/#services-api

**Comment by tonyldo** [comment]
This is a ttlock2mqtt question.. so i m closing this here.
