### ISSUE TITLE
no :  create_user_and_access_token after insttall ttlockio via pip3

### ISSUE THREAD

**Issue by smilexth** [tonyldo/ttlockio#4]
no :  create_user_and_access_token after insttall ttlockio via pip3

any idea ?

Thanks

**Comment by tonyldo** [comment]
Windows or Linux!?

**Comment by smilexth** [comment]
> Windows or Linux!?

Ubuntu 20.04, Sir

**Comment by tonyldo** [comment]
Show me the error, please!

**Comment by smilexth** [comment]
> Show me the error, please!

![Untitled-1](https://user-images.githubusercontent.com/154602/112309334-ce2e5e00-8cd5-11eb-8885-346c36c243f0.png)

**Comment by smilexth** [comment]
Any ideas ?

**Comment by tonyldo** [comment]
look at your .local folder.... like this:
(venv) tonyldo@tonyldo-5480:~$ ls /home/tonyldo/.local/bin/            
If there is no script in there, try unistall and install ttlockio again. Print here the output install log, please.

**Comment by tonyldo** [comment]
closed!
