### ISSUE TITLE
TTLock API URLs broken

### ISSUE THREAD

**Issue by gersonagc** [tonyldo/ttlockio#5]
I think the urls for registering and creating an application have changed:

https://open.ttlock.com/register
https://open.ttlock.com/CreateApplication

**Comment by tonyldo** [comment]
TKS, i m updating the README.

**Comment by gersonagc** [comment]
One of these is https://open.ttlock.com/register (not /reg in the end).

**Comment by tammeryousef1006** [comment]
im facing all these error after hass os upgrades 

s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-03-01 00:34:43 - [ERROR] TTLOCK2MQTT: Error main method
Traceback (most recent call last):
  File "/ttlock_adapter.py", line 326, in main
    createClients(broker, port, broker_user, broker_pass,
  File "/ttlock_adapter.py", line 306, in createClients
    for gateway in ttlock.get_gateway_generator():
  File "/usr/local/lib/python3.9/site-packages/ttlockwrapper/ttlock.py", line 99, in get_gateway_generator
    _response = TTLock.__send_request__(_url_request).json()
  File "/usr/local/lib/python3.9/site-packages/ttlockwrapper/ttlock.py", line 28, in __send_request__
    raise TTlockAPIError(error_code=_response.json().get(ERROR_CODE_FIELD),menssage=_response.json().get(MENSSAGE_FIELD))
ttlockwrapper.ttlock.TTlockAPIError: Error returned from TTlockAPI: Error_code 10004 - invalid grant

**Comment by tonyldo** [comment]
In this case, It is a error with your token. See this:
https://open.ttlock.com/doc/api/error

**Comment by tammeryousef1006** [comment]
Can you help me with token refresh?  Write for me the command line and i
will fill it with my refresh token and post it please

**Comment by tammeryousef1006** [comment]
solved it thank you

**Comment by tonyldo** [comment]
closed!

**Comment by shivani446** [comment]
@tammeryousef1006 How did you solved that error 10004 `invalid grant`?

Can you please elaborate on the solution steps.

**Comment by tammeryousef1006** [comment]
> @tammeryousef1006 How did you solved that error 10004 `invalid grant`?
> 
> Can you please elaborate on the solution steps.

i generate a new refresh token , because old one keeps expiring every 180 days as i remember , now there is new integration via hacs and more easier to setup , try to search it over hacs
