### ISSUE TITLE
Mqtt message

### ISSUE THREAD

**Issue by Chiga75** [tonyldo/ttlockio#7]
Hello again.
Sorry for I Disturb you again. 
Finally I could install the gateway. 
It show one lock like a sensor without any attribute.  
Could you explain me how can I set a new code on the lock with MQTT?

**Comment by tonyldo** [comment]
No problem man, i m here to help!
So now u add the Gateway to yours ttlockio user u need add the Locks to that Gateway u can do this in mobile app to

**Comment by Chiga75** [comment]
I have already done it with the app. 
In the app I can control the lock. 
In the HA system I see the gateway and I see the lock like a sensor I attached a picture.
![test](https://user-images.githubusercontent.com/86006126/157509529-da814656-9128-42a3-b6a8-c6cdf133c6e1.jpg)

**Comment by tonyldo** [comment]
U are only seen the gateway connection sensor because u didnt add yours locks to this gateway u can see this at the gateway menu option in mobile app.
Yours locks are showing in the app because you add its directly (via bluetooth).
https://www.youtube.com/watch?v=-lhKbjVP1as

**Comment by Chiga75** [comment]
So I deleted the door from the app. and added the lock again.
Now under the devices I see 2 device 1 device the gateway and another the lock. (see the picture below)
when I click in the lock it show it has one sensor the battery sensor active and I can send lock an unlock command. 
Is there any way to make pass code via mqtt or I can just lock and ulock the lock?

**Comment by tonyldo** [comment]
Great man!!
For now i implementing only these features:
- Gateway Connected Sensor
- Lock Battery Sensor
- State Lock Sensor
- and the Commands Lock and Unlock

**Comment by Chiga75** [comment]
I see. Thank you for your help.
Do you plan to implementing the add key code to the lock?
